export { ICheckType } from "./CheckType";
export { IDepartment, IMobilPosConfig } from "./Department";
export { Result } from "./Result";
export { IStaff } from "./Staff";
export { IStok } from "./Stok";
export { IStokBarcode } from "./StokBarcode";
export { IStokDepartment } from "./StokDepartment";
export { IStokGrup } from "./StokGrup";
export { ICheck, ICheckDetail, ITable } from "./Table";
export { IUser } from "./User";
